### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by lengjibo** [Dewera/Pluto#2]
Releases

**Comment by lengjibo** [comment]
sorry i can not use the library

**Comment by Dewera** [comment]
I can't help you unless you provide some context.

**Comment by lengjibo** [comment]
I used the command ，but it didn`t seems to be working properly

`PS D:\protect\CSharp\SyscallCsharp> dotnet add SyscallCsharp package Pluto --version 1.2.0
  正在确定要还原的项目…
  Writing C:\Users\Administrator\AppData\Local\Temp\tmp40FE.tmp
info : 正在将包“Pluto”的 PackageReference 添加到项目“D:\protect\CSharp\SyscallCsharp\SyscallCsharp\SyscallCsharp.csproj”。
error: 将程序包“Pluto”添加到项目“D:\protect\CSharp\SyscallCsharp\SyscallCsharp\SyscallCsharp.csproj”时出错。该项目不支持通过添加程序包命令来添加程序包引用。`

![QQ图片20210317085540](https://user-images.githubusercontent.com/31297202/111398521-9ab06a00-86fe-11eb-8b3b-053874094354.png)

**Comment by Dewera** [comment]
It looks like you're trying to add the package from the official Nuget feed - The library is hosted on there so that won't work. Either configure your Nuget sources to have the GitHub [feed](https://docs.github.com/en/packages/guides/configuring-dotnet-cli-for-use-with-github-packages) or download the repository and add it to your project manually.

**Comment by lengjibo** [comment]
Thanks
